# Generated by Django 6.0.5 on 2026-06-01 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Fuente')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_archivo', models.CharField(max_length=10, verbose_name='Tipo de Archivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuente ETL',
                'verbose_name_plural': 'Fuentes ETL',
            },
        ),
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=500, verbose_name='Archivo')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='Registros Procesados')),
                ('registros_limpios', models.IntegerField(default=0, verbose_name='Registros Limpios')),
                ('registros_errores', models.IntegerField(default=0, verbose_name='Registros con Errores')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('log_detalle', models.TextField(blank=True, null=True, verbose_name='Log Detallado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.etlsource', verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Ejecución ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='Índice de Masa Corporal')),
                ('imc_clasificacion', models.CharField(blank=True, choices=[('BAJO_PESO', 'Bajo Peso'), ('NORMAL', 'Normal'), ('SOBREPESO', 'Sobrepeso'), ('OBESIDAD_I', 'Obesidad Grado I'), ('OBESIDAD_II', 'Obesidad Grado II'), ('OBESIDAD_III', 'Obesidad Grado III')], max_length=20, null=True, verbose_name='Clasificación IMC')),
                ('presion_sistolica', models.IntegerField(verbose_name='Presión Sistólica')),
                ('presion_diastolica', models.IntegerField(verbose_name='Presión Diastólica')),
                ('glucosa', models.FloatField(verbose_name='Glucosa (mg/dL)')),
                ('colesterol', models.FloatField(verbose_name='Colesterol (mg/dL)')),
                ('frecuencia_cardiaca', models.IntegerField(verbose_name='Frecuencia Cardíaca')),
                ('saturacion_oxigeno', models.FloatField(verbose_name='Saturación Oxígeno (%)')),
                ('fumador', models.BooleanField(default=False, verbose_name='Fumador')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('riesgo', models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=10, null=True, verbose_name='Nivel de Riesgo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['riesgo'], name='etl_patient_riesgo_1ded5a_idx'), models.Index(fields=['edad'], name='etl_patient_edad_a830bc_idx'), models.Index(fields=['sexo'], name='etl_patient_sexo_0620d7_idx'), models.Index(fields=['imc'], name='etl_patient_imc_38fc1c_idx')],
            },
        ),
    ]
