# Generated by Django 6.0.5 on 2026-06-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='altura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(2.5)], verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='colesterol',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(800)], verbose_name='Colesterol (mg/dL)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='frecuencia_cardiaca',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Frecuencia Cardíaca'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucosa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Glucosa (mg/dL)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_diastolica',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Presión Diastólica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_sistolica',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='Presión Sistólica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='saturacion_oxigeno',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Saturación Oxígeno (%)'),
        ),
    ]
