# Generated by Django 6.0.5 on 2026-06-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_alter_patient_altura_alter_patient_colesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actividad_fisica',
            field=models.CharField(blank=True, choices=[('SEDENTARIO', 'Sedentario'), ('MODERADO', 'Moderado'), ('ACTIVO', 'Activo'), ('INTENSO', 'Intenso')], max_length=20, null=True, verbose_name='Actividad Física'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consumidor_alcohol',
            field=models.BooleanField(default=False, verbose_name='Consumidor de Alcohol'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Consulta'),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura (ºC)'),
        ),
    ]
