# Generated by Django 6.0.5 on 2026-06-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_patient_actividad_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='actividad_fisica',
            field=models.CharField(blank=True, choices=[('SEDENTARIO', 'Sedentario'), ('MODERADO', 'Moderado'), ('ACTIVO', 'Activo'), ('INTENSO', 'Intenso')], default='SEDENTARIO', max_length=20, verbose_name='Actividad Física'),
        ),
    ]
