# Generated by Django 6.0.5 on 2026-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_patient_actividad_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='actividad_fisica',
            field=models.CharField(blank=True, choices=[('SEDENTARIO', 'Sedentario'), ('MODERADO', 'Moderado'), ('ACTIVO', 'Activo'), ('INTENSO', 'Intenso')], max_length=20, null=True, verbose_name='Actividad Física'),
        ),
    ]
