# Generated by Django 6.0.5 on 2026-06-01 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Random Forest Classifier', max_length=100)),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('matriz_confusion', models.JSONField(blank=True, null=True, verbose_name='Matriz de Confusión')),
                ('parametros', models.JSONField(blank=True, null=True, verbose_name='Parámetros')),
                ('entrenado_en', models.DateTimeField(auto_now_add=True, verbose_name='Entrenado en')),
                ('activo', models.BooleanField(default=False, verbose_name='Modelo Activo')),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo ML',
                'verbose_name_plural': 'Modelos ML',
                'ordering': ['-entrenado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion', models.CharField(max_length=10, verbose_name='Predicción')),
                ('probabilidad', models.FloatField(verbose_name='Probabilidad')),
                ('features', models.JSONField(verbose_name='Características')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Predicción')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml.mlmodel', verbose_name='Modelo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.patient', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
