# Generated by Django 6.0.5 on 2026-06-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_prediction_paciente_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='f1_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='F1 Score'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='precision',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Precision'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='recall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recall'),
        ),
    ]
